apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wicked-bovid-go 
  janus-idp.io/tekton: wicked-bovid-go
  backstage.io/kubernetes-id: wicked-bovid-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: wicked-bovid-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  